language: generic
os:
  - osx
  - linux
env:
  - PYTHON_VERSION=2.7
  - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7

notifications:
  slack: echology:avPAhIlErQnf7XSUGcSB5awZ
  email: false

# Install packages
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
    fi
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export MINICONDA_OS="MacOSX";
    else
      export MINICONDA_OS="Linux";
    fi
  - if [[ "$PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-${MINICONDA_OS}-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-${MINICONDA_OS}-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # We need to setup a new environment
  - conda create -n test_env python=$PYTHON_VERSION
  - source activate test_env

  # Install the dependencies
  - conda install --yes pip numpy scipy>=0.18.0 matplotlib nose
  - pip install -r requirements.txt
  - python setup.py install

script:
  - python setup.py build_ext --inplace
  - nosetests

# Deploy to pypi (or test)
deploy:
  # pypi
  - provider: pypi
    on:
      branch: pypi-release
      tags: true
    distributions: "sdist bdist_wheel"
    skip_existing: true
    user: "fakufaku"
    password:
      secure: "DT89f2IjQQ23UHa9CTKcxSDGYzk6HD4gBh4s41Qd34VyIuUvVrYxXNq0dWc+ciSVG1HjzpVEqUZj1+zD9yoDciczvBGE5qXXGhW8XjMQVzA8wzyO9H4ybkKwFlKgK6GM0K7vs+E+E7/T06u4ktiB+Rvu3nzFOLnl8fEMAlXWJH067dK+ltX4iVtHs06Q8yRpKFrVCOpyJuMP4FIqK4YA/azvH0TEG/P5DM6omATZUuoNGgXdE+oD2pkguhcejOwvSSmk7m2M1BPuesoeF4uYI1jEWrev++7zXtvwT0f2FKOXd21SVe3dzZv478C2ttABFFIDXRlYPWgSuwE311hUqlDrkmWgvJ1rdj2A5ajTew00EJBRjfrdRNiHzYJ7p51HLD2oGM+44EPqXCx8+OmD9TmdPGjwP1OGxFsJ0ADWcFQWeaubOjmBPv8P7DLORg5sHqt3IHmlL/F6JOmLkOLJ9nqi1hcHMrJpoWO83RqyZ/2HhVxmjrBMmVqXjmH5QJx1Kj2G1tZov55XHXO+XOfiFpJXtLQggZsOsipQ9ZuPG/WzWgcfLoMEpQCweZDw/ynSnG1JeEYK6csEEWIGfcnkk0zu1wcxPX7SQTEKVqg3uC1IG6lSQicCsBbDc83iEP3B908VLHv1Cav3VIqUh55QsyDjaGs5XJpp7sOnCx2xiB8="
  # pypi test
  - provider: pypi
    server: https://testpypi.python.org/pypi
    on:
      branch: pypi-test
      tags: false
    distributions: "sdist bdist_wheel"
    skip_existing: true
    user: "fakufaku"
    password:
      secure: "pq8IudLa27DUDguiSUiYCEbUI6Y5QX1o298ITPiEZv5PKbSSdpgzBo3MZenKQGgHEhx2u1F0ld9QHRxXFsFHSkqLEGmb6FFl85upR0mMK8mrckSmGXmYTC22t5yzylJ6NFUx0wsGiEdSn/+3KjOwadLSfmjLfLxPp0bFpaC+2KK7TWFvpVhHMzG5Xz6VW3kJ95tZ0u9xhQsA9qB7AuluFXi1KfZHxyq3qgIfe998xIjn0Xu4x9VnL/S0WAF8SE7ftuwLT38yv+fIFFo85okNsfTn/nFIlAsNOh+gGRJuiCivv4IFopAWiimRxkUt3AWP9v4QDlwIhej77t+EowkFyb4eLzTwH+gmaX43Z3+Jy7wtlUTdIWPDuuUGXt1CPn/Cua6Z3WapQObe/oNsrCzXtMxvqOa0JHV7ID85MQ9cZpi6MwqR82PXXIPanWiBy7Et46zioGar3BsFUK2fz+XRpcrYay8sd79sknI9Yt2hNL0NYa7XxKgiTo0CrjCDUFSlMNt0JmozMtvv/C4Fy/6DEEyspQxuBivg2BcFUQd8cyn89PcpJ9L0AOMy/gUV0EFA/6Ax+qMiDli5EoT7bWtmxyJkmWsDLoqsvEBDKkw4z3/1xkbD+F1lAj9MqPIcmwoEXAMqqYqUTDTDNhhZYvsIXgSJOzz1RjUrEm2DiqBi1oE="
